# Generated by Django 2.1.3 on 2018-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='about_me',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profession',
            field=models.CharField(blank=True, max_length=20, verbose_name='Profession'),
        ),
    ]
