# Generated by Django 2.1.3 on 2018-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181129_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Tell us a little bit about yourself'),
        ),
    ]
