# Generated by Django 2.1.3 on 2018-12-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181204_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
