# Generated by Django 2.1.3 on 2018-12-01 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modifiy', models.DateTimeField(auto_now=True)),
                ('text', mdeditor.fields.MDTextField(blank=True)),
                ('html_content', models.TextField(blank=True, verbose_name='html content')),
                ('public_flag', models.IntegerField(default=1)),
                ('published_flag', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
