# Generated by Django 2.1.3 on 2018-12-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181204_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='collection',
        ),
    ]
